### ISSUE TITLE
Weights used in DeNovoWEST

### ISSUE THREAD

**Issue by ksarathbabu** [queenjobo/DeNovoWEST#2]
Thank you for making the tool public so we could utilize it for our project. We have been using Denovolyzer to look for enrichment until now and interested in using DenovoWest for our current analysis. 

Our cohort has only ~400 Trios, can we still use the weights creation tool to generate the cohort specific weights for our analysis or are we better off using the given weights file itself since this was generated from ~31K Trios. 

Thank you
Sarath Babu

**Comment by sarahjlindsay** [comment]
Hi -  when the weights are calculated we supply the numbers of individuals in the cohort so as to accurately calculate the observed/expected number of mutations for each gene., you could use these weights making sure to correctly specify the numbers of individuals when running the your datasets. If you were to regenerate the weights for smaller cohorts, you are also likely to need to adjust the CADD bins as part of making the weights.
We found that smaller datasets lead to noisier results - When we ran the predecessor of this pipeline on a dataset of ~10k trios (from the DDD cohort), we found that the method worked but the estimates of fold-enrichment were much noisier than when we used the full 31k trios in our cohort. 
You could try combining your trios with the published dataset (supplied here https://github.com/HurlesGroupSanger/DeNovoWEST/blob/master/input/DDD_RUMC_GDX_denovos_cadd_shet_wweights_2020_01_17.txt.gz), while making sure the QC/annotations are comparable.
