### ISSUE TITLE
Rates resource file for B38

### ISSUE THREAD

**Issue by sarahjlindsay** [queenjobo/DeNovoWEST#3]
Supply a comparable mutation rates resource file, but lifted over to B38.

**Comment by delagee** [comment]
Add b38 rates file created to Sanger DNW sFTP.
Provide the link through the wiki pages.

**Comment by delagee** [comment]
Edit the Resources wiki page

**Comment by sarahjlindsay** [comment]
This file has now been added to ftp://ftp.sanger.ac.uk/pub/project/ddd/B38_rates/B38_merged_rates.gz
This file has been generated in the same way as the published rates data in ftp://ftp.sanger.ac.uk/pub/project/ddd/rates.
